-- ファイターズ選手タグのふりがな
-- 読みは公式選手名鑑の各選手ページをもとに登録しています。

START TRANSACTION;

ALTER TABLE tags
  ADD COLUMN reading VARCHAR(100) DEFAULT NULL AFTER name;

UPDATE tags
SET reading = CASE name
  WHEN '矢澤 宏太' THEN 'やざわ こうた'
  WHEN '生田目 翼' THEN 'なばため つばさ'
  WHEN '加藤 貴之' THEN 'かとう たかゆき'
  WHEN '北山 亘基' THEN 'きたやま こうき'
  WHEN '達 孝太' THEN 'たつ こうた'
  WHEN '伊藤 大海' THEN 'いとう ひろみ'
  WHEN '山﨑 福也' THEN 'やまさき さちや'
  WHEN '玉井 大翔' THEN 'たまい たいしょう'
  WHEN '上原 健太' THEN 'うえはら けんた'
  WHEN '金村 尚真' THEN 'かねむら しょうま'
  WHEN '宮西 尚生' THEN 'みやにし なおき'
  WHEN '田中 正義' THEN 'たなか せいぎ'
  WHEN '大川 慈英' THEN 'おおかわ じぇい'
  WHEN '河野 竜生' THEN 'かわの りゅうせい'
  WHEN '細野 晴希' THEN 'ほその はるき'
  WHEN 'サウリン・ラオ' THEN 'さうりん らお'
  WHEN '柴田 獅子' THEN 'しばた れお'
  WHEN '藤田 琉生' THEN 'ふじた りゅうせい'
  WHEN '堀 瑞輝' THEN 'ほり みずき'
  WHEN '浅利 太門' THEN 'あさり たもん'
  WHEN '古林 睿煬' THEN 'ぐーりん・るぇやん'
  WHEN '島本 浩也' THEN 'しまもと ひろや'
  WHEN '福谷 浩司' THEN 'ふくたに こうじ'
  WHEN '福島 蓮' THEN 'ふくしま れん'
  WHEN '畔柳 亨丞' THEN 'くろやなぎ きょうすけ'
  WHEN '柳川 大晟' THEN 'やながわ たいせい'
  WHEN '齋藤 友貴哉' THEN 'さいとう ゆきや'
  WHEN '池田 隆英' THEN 'いけだ たかひで'
  WHEN '菊地 大稀' THEN 'きくち たいき'
  WHEN '清水 大暉' THEN 'しみず だいき'
  WHEN '山城 航太郎' THEN 'やましろ こうたろう'
  WHEN '山本 拓実' THEN 'やまもと たくみ'
  WHEN '有原 航平' THEN 'ありはら こうへい'
  WHEN '松岡 洸希' THEN 'まつおか こうき'
  WHEN '清宮 虎多朗' THEN 'せいみや こたろう'
  WHEN '孫 易磊' THEN 'すん いーれい'
  WHEN '加藤 大和' THEN 'かとう やまと'
  WHEN '松本 遼大' THEN 'まつもと りょうだい'
  WHEN '川勝 空人' THEN 'かわかつ そらと'
  WHEN '澁谷 純希' THEN 'しぶや じゅんき'
  WHEN '横山 永遠' THEN 'よこやま とわ'
  WHEN '福田 俊' THEN 'ふくだ すぐる'
  WHEN '安西 叶翔' THEN 'あんざい かなと'
  WHEN '根本 悠楓' THEN 'ねもと はるか'
  WHEN 'アリエル・マルティネス' THEN 'ありえる まるてぃねす'
  WHEN '郡司 裕也' THEN 'ぐんじ ゆうや'
  WHEN '清水 優心' THEN 'しみず ゆうし'
  WHEN '進藤 勇也' THEN 'しんとう ゆうや'
  WHEN 'ライル・リン' THEN 'らいる りん'
  WHEN '藤森 海斗' THEN 'ふじもり かいと'
  WHEN '吉田 賢吾' THEN 'よしだ けんご'
  WHEN '田宮 裕涼' THEN 'たみや ゆあ'
  WHEN '梅林 優貴' THEN 'うめばやし ゆうき'
  WHEN '日渡 騰輝' THEN 'ひわたり とうき'
  WHEN '上川畑 大悟' THEN 'かみかわばた だいご'
  WHEN '野村 佑希' THEN 'のむら ゆうき'
  WHEN 'ロドルフォ・カストロ' THEN 'ろどるふぉ かすとろ'
  WHEN '中島 卓也' THEN 'なかしま たくや'
  WHEN '清宮 幸太郎' THEN 'きよみや こうたろう'
  WHEN '有薗 直輝' THEN 'ありぞの なおき'
  WHEN '水野 達稀' THEN 'みずの たつき'
  WHEN '阪口 樂' THEN 'さかぐち うた'
  WHEN '大塚 瑠晏' THEN 'おおつか るあん'
  WHEN '半田 南十' THEN 'はんだ みなと'
  WHEN '山縣 秀' THEN 'やまがた しゅう'
  WHEN '細川 凌平' THEN 'ほそかわ りょうへい'
  WHEN '奈良間 大己' THEN 'ならま たいき'
  WHEN '明瀬 諒介' THEN 'みょうせ りょうすけ'
  WHEN '常谷 拓輝' THEN 'つねや ひろき'
  WHEN '濵田 泰希' THEN 'はまだ たいき'
  WHEN '西川 遥輝' THEN 'にしかわ はるき'
  WHEN '淺間 大基' THEN 'あさま だいき'
  WHEN '宮崎 一樹' THEN 'みやざき かずき'
  WHEN 'エドポロ ケイン' THEN 'えどぽろ けいん'
  WHEN '五十幡 亮汰' THEN 'いそばた りょうた'
  WHEN '水谷 瞬' THEN 'みずたに しゅん'
  WHEN '今川 優馬' THEN 'いまがわ ゆうま'
  WHEN '万波 中正' THEN 'まんなみ ちゅうせい'
  WHEN 'フランミル・レイエス' THEN 'ふらんみる れいえす'
  WHEN '藤田 大清' THEN 'ふじた たいせい'
  WHEN '山口 アタル' THEN 'やまぐち あたる'
  WHEN '星野 ひので' THEN 'ほしの ひので'
  ELSE reading
END
WHERE user_id IS NULL AND tag_type = 'player';

COMMIT;
