-- ファイターズ選手タグの背番号
-- 公式選手名鑑の掲載番号をタグ検索・表示に利用します。
START TRANSACTION;

ALTER TABLE tags
  ADD COLUMN uniform_number VARCHAR(10) DEFAULT NULL AFTER reading;

UPDATE tags
SET uniform_number = CASE name
  WHEN '矢澤 宏太' THEN '12'
  WHEN '生田目 翼' THEN '13'
  WHEN '加藤 貴之' THEN '14'
  WHEN '北山 亘基' THEN '15'
  WHEN '達 孝太' THEN '16'
  WHEN '伊藤 大海' THEN '17'
  WHEN '山﨑 福也' THEN '18'
  WHEN '玉井 大翔' THEN '19'
  WHEN '上原 健太' THEN '20'
  WHEN '金村 尚真' THEN '24'
  WHEN '宮西 尚生' THEN '25'
  WHEN '田中 正義' THEN '26'
  WHEN '大川 慈英' THEN '27'
  WHEN '河野 竜生' THEN '28'
  WHEN '細野 晴希' THEN '29'
  WHEN 'サウリン・ラオ' THEN '30'
  WHEN '柴田 獅子' THEN '31'
  WHEN '藤田 琉生' THEN '32'
  WHEN '堀 瑞輝' THEN '34'
  WHEN '浅利 太門' THEN '35'
  WHEN '古林 睿煬' THEN '37'
  WHEN '島本 浩也' THEN '40'
  WHEN '福谷 浩司' THEN '41'
  WHEN '福島 蓮' THEN '45'
  WHEN '畔柳 亨丞' THEN '46'
  WHEN '柳川 大晟' THEN '47'
  WHEN '齋藤 友貴哉' THEN '48'
  WHEN '池田 隆英' THEN '52'
  WHEN '菊地 大稀' THEN '55'
  WHEN '清水 大暉' THEN '62'
  WHEN '山城 航太郎' THEN '63'
  WHEN '山本 拓実' THEN '67'
  WHEN '有原 航平' THEN '74'
  WHEN '松岡 洸希' THEN '93'
  WHEN '清宮 虎多朗' THEN '94'
  WHEN '孫 易磊' THEN '96'
  WHEN '加藤 大和' THEN '113'
  WHEN '松本 遼大' THEN '114'
  WHEN '川勝 空人' THEN '121'
  WHEN '澁谷 純希' THEN '122'
  WHEN '横山 永遠' THEN '124'
  WHEN '福田 俊' THEN '140'
  WHEN '安西 叶翔' THEN '154'
  WHEN '根本 悠楓' THEN '159'
  WHEN 'アリエル・マルティネス' THEN '2'
  WHEN '郡司 裕也' THEN '3'
  WHEN '清水 優心' THEN '10'
  WHEN '進藤 勇也' THEN '33'
  WHEN 'ライル・リン' THEN '38'
  WHEN '藤森 海斗' THEN '57'
  WHEN '吉田 賢吾' THEN '60'
  WHEN '田宮 裕涼' THEN '64'
  WHEN '梅林 優貴' THEN '98'
  WHEN '日渡 騰輝' THEN '120'
  WHEN '上川畑 大悟' THEN '4'
  WHEN '野村 佑希' THEN '5'
  WHEN 'ロドルフォ・カストロ' THEN '6'
  WHEN '中島 卓也' THEN '9'
  WHEN '清宮 幸太郎' THEN '21'
  WHEN '有薗 直輝' THEN '39'
  WHEN '水野 達稀' THEN '43'
  WHEN '阪口 樂' THEN '44'
  WHEN '大塚 瑠晏' THEN '49'
  WHEN '半田 南十' THEN '51'
  WHEN '山縣 秀' THEN '54'
  WHEN '細川 凌平' THEN '56'
  WHEN '奈良間 大己' THEN '58'
  WHEN '明瀬 諒介' THEN '65'
  WHEN '常谷 拓輝' THEN '95'
  WHEN '濵田 泰希' THEN '111'
  WHEN '西川 遥輝' THEN '7'
  WHEN '淺間 大基' THEN '8'
  WHEN '宮崎 一樹' THEN '36'
  WHEN 'エドポロ ケイン' THEN '42'
  WHEN '五十幡 亮汰' THEN '50'
  WHEN '水谷 瞬' THEN '53'
  WHEN '今川 優馬' THEN '61'
  WHEN '万波 中正' THEN '66'
  WHEN 'フランミル・レイエス' THEN '99'
  WHEN '藤田 大清' THEN '125'
  WHEN '山口 アタル' THEN '127'
  WHEN '星野 ひので' THEN '168'
  WHEN '新庄 剛志' THEN '1'
  WHEN '的場 直樹' THEN '71'
  WHEN '山田 勝彦' THEN '72'
  WHEN '武田 久' THEN '73'
  WHEN '小田 智之' THEN '75'
  WHEN '紺田 敏正' THEN '76'
  WHEN '林 孝哉' THEN '77'
  WHEN '清水 雅治' THEN '78'
  WHEN '松本 哲也' THEN '79'
  WHEN '森本 稀哲' THEN '80'
  WHEN '横尾 俊建' THEN '81'
  WHEN '加藤 武治' THEN '82'
  WHEN '浦野 博司' THEN '83'
  WHEN '岩舘 学' THEN '84'
  WHEN '谷内 亮太' THEN '85'
  WHEN '佐藤 友亮' THEN '87'
  WHEN '稲葉 篤紀' THEN '90'
  WHEN '金子 千尋' THEN '91'
  WHEN '江口 孝義' THEN '92'
  ELSE uniform_number
END
WHERE user_id IS NULL AND tag_type = 'player';

COMMIT;
